//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBClient.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiBeBe_DatabaseEntities : DbContext
    {
        public MiBeBe_DatabaseEntities()
            : base("name=MiBeBe_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<CitaProgramada> CitaProgramadas { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Examan> Examen { get; set; }
        public virtual DbSet<InfoSalud> InfoSaluds { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Tratamiento> Tratamientoes { get; set; }
        public virtual DbSet<US> US { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
    }
}
