//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBClient.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class US
    {
        public int Id_US { get; set; }
        public string Nombres { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
    }
}
